language: go

env:
  - GO111MODULE=on

install:
  - go get golang.org/x/lint/golint

script:
  - go build ./...
  - go test -v ./...
  - go test -cover -race ./...
  - go vet ./...
  - test -z "$(gofmt -d -s *.go)"
  - golint ./...

sudo: false
