language: go

go:
  - 1.12.x
  - 1.13.x
  - 1.x

env:
  - GO111MODULE=on

install:
  - go get golang.org/x/lint/golint
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - go build ./...
  - go test -v ./...
  - go vet ./...
  - test -z "$(gofmt -d -s *.go)"
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- v1.19.1
  - ./bin/golangci-lint run ./...
  - go test -v -covermode=count -coverprofile=coverage.out
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

sudo: false
